//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonInMovie
    {
        public int id { get; set; }
        public int id_movie { get; set; }
        public int id_person { get; set; }
        public int id_job { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual Movie Movie { get; set; }
        public virtual Person Person { get; set; }
    }
}
