//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewRating
    {
        public int id { get; set; }
        public int id_review { get; set; }
        public int id_user { get; set; }
        public bool is_likes { get; set; }
    
        public virtual Review Review { get; set; }
        public virtual User User { get; set; }
    }
}
