//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int id { get; set; }
        public int id_session { get; set; }
        public int id_user { get; set; }
        public int id_place { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Place Place { get; set; }
        public virtual Session Session { get; set; }
        public virtual User User { get; set; }
    }
}
